apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ template "fullname" . }}-cron
  labels:
    draft: {{ default "draft-app" .Values.draft }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
spec:
  schedule: "*/15 * * * *"
  jobTemplate:
    spec:
      template:
        metadata:
          annotations:
            buildID: {{ .Values.buildID }}
          labels:
            draft: {{ default "draft-app" .Values.draft }}
            app: {{ template "fullname" . }}
        spec:
          restartPolicy: OnFailure
          containers:
          - name: {{ .Chart.Name }}
            image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
            imagePullPolicy: {{ .Values.image.pullPolicy }}
            command: ["python"]
            args: ["manage.py","refresh_data_sources"]
            env:
            - name: "DATABASE_URL"
              valueFrom:
                secretKeyRef:
                  key:  database_url
                  name: {{ .Release.Name }}-auth
            resources:
{{ toYaml .Values.resources | indent 16 }}
          nodeSelector:
          {{- if .Values.nodeSelector }}
{{ toYaml .Values.nodeSelector | indent 12 }}
          {{- end }}
