apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-auth
type: Opaque
data:
  database_url: {{ .Values.db.url | b64enc | quote }}
  collab_admin_username: {{ .Values.collab.admin.username | b64enc | quote }}
  collab_admin_email: {{ .Values.collab.admin.email | b64enc | quote }}
  collab_admin_password: {{ .Values.collab.admin.password | b64enc | quote }}
