apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "fullname" . }}
  labels:
    draft: {{ default "draft-app" .Values.draft }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
spec:
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      annotations:
        buildID: {{ .Values.buildID }}
      labels:
        draft: {{ default "draft-app" .Values.draft }}
        app: {{ template "fullname" . }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        env:
        - name: "PORT"
          value: "{{ .Values.service.internalPort }}"
        - name: "DATABASE_URL"
          valueFrom:
            secretKeyRef:
              key:  database_url
              name: {{ .Release.Name }}-auth
        - name: "COLLAB_ADMIN_USERNAME"
          valueFrom:
            secretKeyRef:
              key:  collab_admin_username
              name: {{ .Release.Name }}-auth
        - name: "COLLAB_ADMIN_EMAIL"
          valueFrom:
            secretKeyRef:
              key:  collab_admin_email
              name: {{ .Release.Name }}-auth
        - name: "COLLAB_ADMIN_PASSWORD"
          valueFrom:
            secretKeyRef:
              key:  collab_admin_password
              name: {{ .Release.Name }}-auth
        ports:
        - containerPort: {{ .Values.service.internalPort }}
        resources:
{{ toYaml .Values.resources | indent 12 }}
      nodeSelector:
      {{- if .Values.nodeSelector }}
{{ toYaml .Values.nodeSelector | indent 8 }}
      {{- end }}
