# Default values for node.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
image:
  pullPolicy: Always
service:
  name: node
  type: ClusterIP
  externalPort: 8080
  internalPort: 8080
nodeSelector:
  cloud.google.com/gke-nodepool: default-pool
resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi
ingress:
  enabled: true
basedomain: publicintegrity.org
db:
  url: ""
collab:
  admin:
    username: ""
    email: ""
    password: ""
